apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-event-booking-ingress
  namespace: online-event-booking-raheem
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: localhost
    http:
      paths:
      # Frontend routed on root path
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend      
            port:
              number: 80       
      # Backend services routed on subpaths
      - path: /api/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 3001
      - path: /api/events
        pathType: Prefix
        backend:
          service:
            name: event-service
            port:
              number: 3002
      - path: /api/bookings
        pathType: Prefix
        backend:
          service:
            name: booking-service
            port:
              number: 3003
      - path: /api/notifications
        pathType: Prefix
        backend:
          service:
            name: notification-service
            port:
              number: 3004